### ISSUE TITLE
investigate orm env var sample app integ test

### ISSUE THREAD

**Issue by jhsinger-klotho** [klothoplatform/klotho#206]
https://github.com/klothoplatform/klotho/actions/runs/4101170675/jobs/7072734224

**Comment by yuval-klotho** [comment]
Able to locally repro

**Comment by yuval-klotho** [comment]
Seeing connection errors:

```
ERROR	unable to get key:myTestKey. Received error:SequelizeConnectionError: Connection terminated unexpectedly
```
and
```
ERROR	unable to set key:myTestKey, value:myTestValue. Received error:SequelizeConnectionError: Connection terminated unexpectedly
```

Our env var specifies:

```
ORM_CONNECTION_STRING=postgresql://testuser:testpassword@sequelizedb-1f66662.proxy-csiwfo2v7ytx.us-east-2.rds.amazonaws.com:5432/sequelizedb
```

Looking at secrets manager, we see the following connection info:

```
{
  "username": "testuser",
  "password": "testpassword",
  "engine": "postgres",
  "host": "sequelizedb4b49cf3.csiwfo2v7ytx.us-east-2.rds.amazonaws.com",
  "port": 5432,
  "dbname": "sequelizedb",
  "dbInstanceIdentifier": "sequelizedb4b49cf3",
  "iamDatabaseAuthenticationEnabled": false
}

```

**Comment by yuval-klotho** [comment]
Ah-ha. Note that `ORM_CONNECTION_STRING` used a db instance name of `sequelizedb`, while the secret specifies `dbInstanceIdentifier`. This is a sanitization mismatch.

**Comment by jhsinger-klotho** [comment]
im a bit confused on how sanitization breaks this, wouldnt this just inject the generated connection string of the proxy into our env var? Then the secret is what the proxy uses to talk to the actual instance

**Comment by jhsinger-klotho** [comment]
oh does the end of the connection string have to be the identifier and not the name?

**Comment by yuval-klotho** [comment]
yeah

**Comment by yuval-klotho** [comment]
test run for possible fix: https://github.com/klothoplatform/klotho/actions/runs/4107577790

**Comment by yuval-klotho** [comment]
Oh, no that's not it. If I try that, I get an error saying that the db "sequelizedb4b49cf3" doesn't exist.

I think what's happening is that the lambda instance gets spun up before the DDB instance is ready. That means that the connection can't get established — and the Lambda then caches that un-established connection. That survives until the Lambda container ages out and it has to spin up a new instance, which then is able to connect.

I'll verify that. If that's the case, then we either need to wait so that the RDS instance is fully spun up, or else have the Lambda retry its connection.

**Comment by jhsinger-klotho** [comment]
i thought it did want because pulumi sees were using an output in the lambda environment, but maybe not? Otherwise wouldnt we have had this issue always?
