### ISSUE TITLE
better handling of analytics properties

### ISSUE THREAD

**Issue by yuval-klotho** [klothoplatform/klotho#239]
We have a mechanism to attach custom information to our log messages, which then gets sanitized and sent to our analytics server. Unfortunately, the only way we can send it today is by including it in the analytic event's name text. This is (I think) supposed to be human readable and succinct, but when we use the sanitization mechanism, it comes through as json.

This has a couple disadvantages:

1. It's hard to see the data in our dashboard; the views are optimized assuming that the event name is human-readable
2. I think (citation needed) it's hard to _use_ in our dashboard; the "event name" field doesn't get auto-parsed

I suspect issue 1 was the motivation behind [`logging.EntryMessageField`][1], which just replaces the analytics message text with the log message. In addition to other problems, this also means that it clobbers any other information that might have been on the sanitized field. I don't think it's a problem in actual usage today, but it's a hidden landmine.

We should consider an alternate way to send these properties, in a way that makes them actually be properties. For example, we could turn each `$key` into a real analytics property, `klotho.$key`. This would require a bit of hackery because of how we currently create and send these messages, but nothing difficult.

[1]: https://github.com/klothoplatform/klotho/blob/acafab93adcee780099b8316dc37a8f06f5da56c/pkg/analytics/fields_listener.go#L49-L53

**Comment by gordon-klotho** [comment]
> I suspect issue 1 was the motivation behind [logging.EntryMessageField](https://github.com/klothoplatform/klotho/blob/acafab93adcee780099b8316dc37a8f06f5da56c/pkg/analytics/fields_listener.go#L49-L53),

`logging.EntryMessageField` was added to get more information on errors encountered - more than just "a compilation failed". I believe that's all it's used for at the moment. It's not the best solution (IMO), but it was a quick and dirty resolution to the problem at the time. We can and should revisit that mechanism.

> In addition to other problems, this also means that it clobbers any other information that might have been on the sanitized field. I don't think it's a problem in actual usage today, but it's a hidden landmine.

💯  absolutely

> We should consider an alternate way to send these properties, in a way that makes them actually be properties.

`zap` is a structured logger, using the fields. It looks like the way we hook up the analytics client to `zap` ([fields_listener](https://github.com/klothoplatform/klotho/blob/main/pkg/analytics/fields_listener.go#L55-L68)) doesn't send the fields as properties. This is likely due to the analytics client lacking a per-message mechanism for setting properties ([client](https://github.com/klothoplatform/klotho/blob/main/pkg/analytics/client.go#L122)).

**Comment by gordon-klotho** [comment]
Copying from https://github.com/klothoplatform/klotho/pull/245#discussion_r1109071563:

> I do think that we should separate "what we send to analytics" from "what we show to the user"

Yeah, I think there's a few cases:

1. A log message that needs to be sanitized / anonymized
2. A log message that should be omitted, but the fields, sanitized, are still relevant
3. An event that is not a log message

We do all three of these already, but doing (3) outside of `klothomain` is not currently possible because the analyticsClient is not passed down into the compiler independent from the logger.

There's a 4th case that I'm not sure whether we care about:

4. A log message that should be completely ignored by analytics

There may be a use-case for it, but we haven't had one yet as far as I know.

**Comment by yuval-klotho** [comment]
I wouldn't get too hung up on the log message portion, specifically. Personally, I feel like a human-readable log message should be kept separate from the machine-readable message that gets sent to analytics, but I'm not too worried about that. I think the bigger thing is that our properties should get sent as actual analytics properties, not just shoehorned into the event name as json.

As part of this, we should also probably send full error stack traces to analytics, both from the `zap.Error` fields and from our panic handler.

This also blocks #218 (at least, as I think about it — happy to discuss in sync), if we want to send login info via analytics properties (which is what Ala had suggested).
