### ISSUE TITLE
Update reconciler to check for resources being used and return an error if they are

### ISSUE THREAD

**Issue by gordon-klotho** [klothoplatform/klotho#809]
Reconciler can use IaC to determine whether something is used outside of a namespace and fail if something is when deleting a namespace resource

**Comment by jhsinger-klotho** [comment]
This is not possible using IaC because we dont know how deep we need to go in deleting the dependencies. because you have to keep going down the iac dependency line to ensure things get deleted ( subnet -> rds subnet group -> rds instance) which will then delete things we dont want deleted (vpc -> vpc link -> api integration -> rest api)


The intended UX right now is to delete everything which lives in the group and we cannot understand that yet. we would have to error
